# Generated by Django 3.1.1 on 2020-09-27 00:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_rows', models.IntegerField(default=6, editable=False)),
                ('no_of_columns', models.IntegerField(default=7, editable=False)),
                ('column', models.IntegerField()),
                ('validity', models.CharField(blank=True, choices=[('Valid', 'Valid'), ('Incalid', 'Invalid')], max_length=255, null=True)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Y', 'First Player'), ('R', 'Second Player')], default='', max_length=1, null=True), size=7), null=True, size=6)),
                ('no_of_moves', models.IntegerField(default=1)),
                ('player', models.CharField(blank=True, choices=[('Y', 'First Player'), ('R', 'Second Player')], max_length=255, null=True)),
            ],
        ),
    ]
